name: Akshay Verma
description: This is my personal website
baseurl: "http://www.averma.me"
paginate_path: "blog/page:num"
safe: true
markdown: rdiscount
permalink: pretty 
timezone: America/New_York

